<?php
/**
 * Starter feature flags generated by scripts/spinup.mjs.
 *
 * tad-2026: dark_mode is off — the site is dark-only (aurora). Turn it back on
 * and add light tokens to assets/src/css/tokens.css if that ever changes.
 *
 * @package TAD
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'features'   => array(
		'acf_options'        => true,
		'acf_blocks'         => true,
		'curated_editor'     => true,
		'dark_mode'          => false,
		'menus'              => true,
		'widgets'            => false,
		'comments'           => false,
		'patterns'           => false,
		'emoji'              => false,
		'sticky_header'      => true,
		'default_thumbnail'  => true,
	),
	'post_types' => array(
		'people' => false,
		'work'   => false,
		'events' => false,
	),
);
