import fs from "node:fs/promises";
import path from "node:path";
import readline from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";

const root = path.resolve(new URL("..", import.meta.url).pathname);
const configPath = path.join(root, "starter.config.json");
const phpConfigPath = path.join(root, "inc/starter-config.php");

const labels = {
  people: "People CPT",
  work: "Work CPT",
  events: "Events CPT",
  widgets: "Widget areas",
  comments: "Comments",
  patterns: "Block patterns",
  dark_mode: "Light/dark mode toggle",
  curated_editor: "Curated editor",
  acf_blocks: "ACF blocks",
  acf_options: "Site Options"
};

async function askBoolean(rl, label, current) {
  const answer = await rl.question(`${label}? ${current ? "[Y/n]" : "[y/N]"} `);
  if (!answer.trim()) return current;
  return ["y", "yes"].includes(answer.trim().toLowerCase());
}

function phpBool(value) {
  return value ? "true" : "false";
}

function phpConfig(config) {
  const features = Object.entries(config.features)
    .map(([key, value]) => `\t\t'${key}' => ${phpBool(value)},`)
    .join("\n");
  const postTypes = Object.entries(config.postTypes)
    .map(([key, value]) => `\t\t'${key}' => ${phpBool(value)},`)
    .join("\n");

  return `<?php
/**
 * Starter feature flags generated by scripts/spinup.mjs.
 *
 * @package TAD
 */

if ( ! defined( 'ABSPATH' ) ) {
\texit;
}

return array(
\t'features' => array(
${features}
\t),
\t'post_types' => array(
${postTypes}
\t),
);
`;
}

const config = JSON.parse(await fs.readFile(configPath, "utf8"));
const rl = readline.createInterface({ input, output });

config.localUrl = (await rl.question(`Local URL [${config.localUrl}]: `)) || config.localUrl;

for (const key of ["acf_options", "acf_blocks", "curated_editor", "dark_mode", "widgets", "comments", "patterns"]) {
  config.features[key] = await askBoolean(rl, labels[key], config.features[key]);
}

for (const key of ["people", "work", "events"]) {
  config.postTypes[key] = await askBoolean(rl, labels[key], config.postTypes[key]);
}

rl.close();

await fs.writeFile(configPath, `${JSON.stringify(config, null, 2)}\n`);
await fs.writeFile(phpConfigPath, phpConfig(config));

console.log("Updated starter.config.json and inc/starter-config.php.");
